MAX_NUM_IMAGES = 3000
DEFAULT_NUM_IMAGES = 1000

# presets = Number of columns, Pixel width presets
# default_index = index of default to start with
[DISPLAY_PRESETS]
presets = [
    '1, 2560',
    '2, 1280',
    '3, 850',
    '4, 640',
    '5, 512',
    '10, 256',
    '20, 128',
    '40, 64'
]
default_index = 4